### ISSUE TITLE
Missing auth module

### ISSUE THREAD

**Issue by middleJack** [codeforamerica/geodata-checkout#1]
/geodata-checkout# node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../auth'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/www/geodata-checkout/routes/index.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by mapmeld** [comment]
I removed the routes requirement from app.js because it wasn't doing anything, other than requiring auth.

Feel free to close this issue if this resolves the problem.
